### ISSUE TITLE
hudextension CTD issue

### ISSUE THREAD

**Issue by Saqer80** [expired6978/SKSE64Plugins#18]
The hudextension.dll is causing CTD after updating for the latest Racemenu mod... Is it gonna be fixed or updated too?

**Comment by Sasha1378** [comment]
I may be wrong but I think you don’t need this version to install xpmsse anymore. It looks like it’s integrated in xpmsse (or at least some files are, as I reinstalled the game from scratch and have some skee files in my game folder without having installed skee)

**Comment by Saqer80** [comment]
Some files were missing while installing.

**Comment by ousnius** [comment]
hudextension was never updated to the latest game version properly. You don't need it for anything RaceMenu does.

**Comment by Saqer80** [comment]
Maybe... But it was working correctly before until I updated Racemenu.

**Comment by Saqer80** [comment]
It was a compatibility issue with SkyHUD... Moving these files: floatingwidget.swf, hud_extension.swf, hud_extension_config.txt From "Data\Interface\Exported" To "Data\Interface" fixed the issue
