### ISSUE TITLE
CTD when activating BodyGen

### ISSUE THREAD

**Issue by bliblablob** [expired6978/SKSE64Plugins#20]
I've got a reproducible crash to report:

Using the Bodygen feature with morphs created for the vanilla CBBE armors via BodySlide will always crash my game after minutes or even seconds of playing. I've created a minimal load order to make sure the problem stems from that feature:
https://pastebin.com/tTMZ3drK
This is my skee64.ini:
https://pastebin.com/HZqL03NS

In my test game I just run from Solitude towards Dragonbridge. It will crash no later than Dragonbridge. Setting bEnableBodyGen=0 will completely fix all crashes, which I have also confirmed with different saves in different locations. But obviously this no solution since I'd like to use the feature.
Setting bParallelMorphing to 0 or changing iLoadMode will make the CTD happen sooner.

I've created both my morphs.ini and templates.ini in meshes\actors\character\BodyGenData\RaceMenu.esp. If somebody needs them for reproducing the crash I can attach them.

Finally skee64.log with bEnableBodyGen=1 and a crash in the end:
https://pastebin.com/fwDes2qa

And same run from Solitude to Dragonbridge with bEnableBodyGen=0 and no crash in the end:
https://pastebin.com/WWpg1zhG

Not that I really have a perfectly stable game, no crashes whatsoever. As soon as BodyGen is activated there will be crashes left and right.

**Comment by bliblablob** [comment]
See more reports of crashes using BodyGen:
https://forums.nexusmods.com/index.php?/topic/6882167-racemenu/page-59#entry62983516

**Comment by expired6978** [comment]
Will need a crash dump

add this to skse64.ini

[Debug]
WriteMinidumps=1

**Comment by bliblablob** [comment]
I've attached a few crash dumps, hope that helps
[Crashdumps.zip](https://github.com/expired6978/SKSE64Plugins/files/2475881/Crashdumps.zip)

**Comment by hex0id** [comment]
@expired6978 any news about this one? I strongly believe I experience the same, though in my situation bodygen was enabled mid game.

**Comment by ulfbearth** [comment]
i went for a run starting from riverwood to dragonsbridge and not a single ctd thanks to SKEE ALPHA10a

**Comment by bliblablob** [comment]
The most recent release has fixed the issue; thank you expired!
