### ISSUE TITLE
nioverride isn't functioning

### ISSUE THREAD

**Issue by mikeaaml** [expired6978/SKSE64Plugins#4]
i can't seem to get the nioverride that comes with racemenu to work, any highheels that require are clipping in the ground

**Comment by lightsourced** [comment]
I'm also experiencing this! :)

**Comment by 57Owens** [comment]
I am also experiencing Nioverride not working for High Heels in Skyrim SSE. I saw a post where someone was using NiExtrafloat, but that isn't working either for high heels

**Comment by mikeaaml** [comment]
It worked on the previous version of skse64 so that definitely isn't true

**Comment by darkconsole** [comment]
yeah someone had commented on a thread from a while back i titled “working hh without hdt” or something to that effect and i had to add “usually works except for currently” XD
