### ISSUE TITLE
CTD on Unequip Heel

### ISSUE THREAD

**Issue by lightsourced** [expired6978/SKSE64Plugins#6]
I am getting a CTD whenever I unequip a high heel. I can equip it just fine and it works perfectly, raises up off the ground, I can walk around just fine, etc. But when I switch to a non-heel type shoe I get a CTD... Haven't experimented with what happens if unequipped to a different high heel, maybe in the morning... This is with the new Alpha 6 build

**Comment by aers** [comment]
Try re-downloading the newest alpha, the first upload had this issue

**Comment by lightsourced** [comment]
Yup! That worked, thank you! 👍
